### ISSUE TITLE
Minecraft 1.20

### ISSUE THREAD

**Issue by MoSadie** [MoSadie/Island-Menu#10]
I'm not sure if/when the Noxcrew will require 1.20 for MCCi, but I have a guess that either it will happen at the launch of open beta or during it.

Mainly marking this down so if anyone asks I can redirect them here.
You can subscribe for notification to this issue to be updated when the mod updates to 1.20.

**Comment by kispintyi** [comment]
They will definitely support it when the Early Access starts and later I think they will use this version to create cosmetics with the help of the armor trim :3
